[keyboard]
bindings = [
    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
    # { key = "F11", mods = "None", action = "ToggleFullscreen" },
    { key = "F11", mods = "None", action = "ToggleViMode" },
]

[cursor]
style = { blinking = "On" }
vi_mode_style = { blinking = "Off" }

[[hints.enabled]]
regex = "https?:[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
action = "copy"
post_processing = true
mouse = { enabled = true, mods = "Shift" }

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
command = "xdg-open"
post_processing = true
mouse = { enabled = true, mods = "None" }

[scrolling]
history = 50000

[font]
size = 10
