#!/bin/bash
set -euo pipefail

case "${BLOCK_BUTTON:-}" in
"1") # Left click
    xdg-terminal-exec sh -c 'echo SYSTEM-WIDE FAILED UNITS:; systemctl --failed; echo; echo USER FAILED UNITS:; systemctl --user --failed; echo; read -p "Press enter to close..."' &
    ;;
"3") # Right click
    systemctl --user reset-failed
    systemctl --failed --quiet && systemctl reset-failed
    ;;
esac

function match() {
    local regex="([0-9]+) loaded units listed.*"
    if [[ $1 =~ $regex ]]; then
        failed_count="${BASH_REMATCH[1]}"
        echo "$failed_count"
    else
        return 1
    fi
}

res1=$(match "$(systemctl --failed)") &&
    res2=$(match "$(systemctl --user --failed)") ||
    (echo failed to match && exit 33)
res=$((res1 + res2))

if [[ $res -gt 0 ]]; then
    echo "systemctl --failed: $res"
    echo "$res"
    exit 33
fi
