#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/block_format.sh"

# One of the following: xrandr, xbacklight, kernel
METHOD="xbacklight"

case "${BLOCK_BUTTON:-}" in
1)
    xbacklight -inc 5
    ;;
3)
    xbacklight -dec 5
    ;;
esac

URGENT_VALUE=10

if [[ "${METHOD}" = "xrandr" ]]; then
    device="${BLOCK_INSTANCE:-primary}"
    xrandrOutput=$(xrandr --verbose)

    if [[ "${device}" = "primary" ]]; then
        device=$(echo "${xrandrOutput}" | grep 'primary' | head -n 1 | awk -F ' ' '{print $1}')
    fi

    curBrightness=$(echo "${xrandrOutput}" | grep "${device}" -A 5 | grep -i "Brightness" | awk -F ':' '{print $2}')
elif [[ "${METHOD}" = "kernel" ]]; then
    device="${BLOCK_INSTANCE:-intel_backlight}"
    maxBrightness=$(cat /sys/class/backlight/${device}/max_brightness)
    curBrightness=$(cat /sys/class/backlight/${device}/brightness)
elif [[ "${METHOD}" = "xbacklight" ]]; then
    curBrightness=$(xbacklight -get)
fi

if [[ "${curBrightness}" -le 0 ]]; then
    exit
fi

if [[ "${METHOD}" = "xrandr" ]]; then
    percent=$(echo "scale=0;${curBrightness} * 100" | bc -l)
elif [[ "${METHOD}" = "kernel" ]]; then
    percent=$(echo "scale=0;${curBrightness} * 100 / ${maxBrightness}" | bc -l)
elif [[ "${METHOD}" = "xbacklight" ]]; then
    percent=$(echo "scale=0;${curBrightness}" | bc -l)
fi

percent=${percent%.*}

if [[ "${percent}" -le 0 ]]; then
    exit 0
fi

if [[ "${percent}" -le "${URGENT_VALUE}" ]]; then
    block_output_emit_urgent "${percent}%" "${percent}%" "${BLOCK_COLOR_WARNING}"
else
    block_output_emit "${percent}%"
fi
