#!/bin/bash

# export LC_TIME="el_GR.UTF-8"

if [ -n "$BLOCK_BUTTON" ]; then
  gsimplecal &
fi

FORMAT="${BLOCK_INSTANCE:-%A, %d %B %Y | %H:%M}" # long
echo $(date "+${FORMAT}")
FORMAT='%a, %d %b %y | %H:%M' # short
echo $(date "+${FORMAT}")
