#!/bin/bash

device="${BLOCK_INSTANCE:-wlan0}"
status=$(cat /sys/class/net/${device}/operstate)

URGENT_VALUE=20

if [[ ${status} == "up" ]]; then
  if [[ -d "/sys/class/net/${device}/wireless" ]]; then
    quality=$(awk 'NR==3 {print $3 "00 %"}''' /proc/net/wireless)
    echo "${quality}"

    if [[ ${quality} -le ${URGENT_VALUE} ]]; then
      exit 33
    fi
  else
    echo "on"
  fi
fi
