#!/bin/bash
ping_average=$(ping -c 3 google.com | tail -1 | awk '{print $4}' | cut -d '/' -f 2)
ping_average=${ping_average%.*}

echo "$ping_average"
if [ "$ping_average" -gt 150 ]; then
  exit 33
fi
